# Generated by Django 5.1.6 on 2025-03-10 11:38

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinodetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kinodetail.rating'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='director',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='director',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='director',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='bio_ky',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('144p', '144p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=32),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
